name: audioplayers
description: A flutter plugin to play multiple audio files simultaneously
version: 0.8.1
author: Luan Nico <luannico27@gmail.com>
homepage: https://github.com/luanpotter/audioplayer

flutter:
  plugin:
    androidPackage: xyz.luan.audioplayers
    pluginClass: AudioplayersPlugin

dependencies:
  uuid: ^2.0.0
  path_provider: ^0.5.0+1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.12.0+1
  test: ^1.5.3

environment:
  sdk: ">=2.0.0-dev.50.0 <3.0.0"
